### ISSUE TITLE
add license 

### ISSUE THREAD

**Issue by SkyBulk** [typedb-osi/typedb-data-cti#1]
it's a very interesting project!

Would you consider adding a license to this repository to specify under which terms this code can be used in order to implement into my project , but would you mind make it permissible (MIT, APACHE 2 , BSD-3 ) if possible ??

**Comment by tomassabat** [comment]
Hi @SkyBulk, nice to hear from you :) Please note we're still finalising the documentation/examples, and the STIX2 schema is not complete yet. This should be done this week.

And yes, we'll add an Apache 2 license tonight. Let us know how you intend to use the project, we'd love to hear from you. Have you joined our [discord community server](www.vaticle.com/discord)?

**Comment by tomassabat** [comment]
I've just pushed Apache license file to the repo @SkyBul :)
